### ISSUE TITLE
Public documents

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#15]
We'd like to share the link of this repo on the demo booth as well as other publications (blogs etc). It'd be great if we have a set of documents for:

- Setting up the demo from scratch (eg creating a GCP project, set up BQ schema etc)
- Explains how it works

But this is not a high priority. We can get started after implementing all the features. Maybe next week?

**Comment by nagachika** [comment]
I added instructions to setup/run demo app and how to customize at https://github.com/groovenauts/QueryItSmart/commit/112350d49983687182fdc740a297affd4cc79436 and https://github.com/groovenauts/QueryItSmart/commit/395bef1b8cbff958732b964341a209cb7ea5451a
After the demo is published, I'd like to make the following BigQuery dataset public. With these BigQuery datasets/tables, anyone can run the demo app on their GCP Project.
```
queryit-smart:wikimedia
queryit-smart:stackoverflow
queryit-smart:citibike
```

We need to some more work to allow user to customize image search on their own images; replace base URL to load search result images. And we need to add the way to specify basic authorization user/password.
