### ISSUE TITLE
Can you make the top page more like the original QueryIt?

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#21]
On the original QueryIt, there were three screens changing every few seconds when the service is in idle.

- "QueryIt" banner screen: the demo title and "Powered by BigQuery"
- "Try BigQuery" screen: with "cloud.google.com/bigquery" URL
- the current top screen

Also, it'd be great to have moves and transitions like the original QueryIt while the service is in idle.

**Comment by kazunori279** [comment]
Basically, we like to reproduce the same UI look & feel as the original QueryIt, including fonts, transitions, design etc.

**Comment by nagachika** [comment]
I got it. We will brush up the look & feel after preparing all sub-category pages.

**Comment by kazunori279** [comment]
Now the site looks quite like the original. Thanks!
