### ISSUE TITLE
Revome HTML tags from the text search result

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#27]

**Comment by nagachika** [comment]
@nakanori The tags can be eliminated in queries.
But some tags can be a hint to how to display the document.
I mean..., for example I can replace `<p>...</p>` to `...<br />` to show break line.
`<code>...</code>` can be highlighted by changing font or background color etc.
How about this idea?

**Comment by kazunori279** [comment]
please also remove the entity references (&xxx;)

**Comment by nagachika** [comment]
Remove HTML tags and entity references  in https://github.com/groovenauts/QueryItSmart/issues/29
