### ISSUE TITLE
Please use only Public Domain images

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#42]
Sorry to bring up this at late, but we need to use only PD images. Otherwise we need to put all links and credits for all Creative Commons images shown on a screen.

https://commons.wikimedia.org/wiki/Category:Public_domain

**Comment by nagachika** [comment]
Hmm, I'd like to handle this by show links and credits for images for two reasons.

- Downloading and vectorizing images is time consuming
- It seems hard to find interesting images in PD categories for key images & search results

I'll confirm the rule for reusing content out of wikimedia.
https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia

**Comment by nagachika** [comment]
I prepared Public Domain image vectors table in BigQuery and search on the table by https://github.com/groovenauts/QueryItSmart/pull/68

**Comment by kazunori279** [comment]
Looks great!!
