### ISSUE TITLE
Replace the "Analyzing...." label

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#5]
with "Searching...".

Also, replace "1 million images / xxx sec" with "On 1 million Wikimedia images with BigQuery. Elapsed xxx sec"

**Comment by kazunori279** [comment]
- Add a new line between "images" and "with"
- Add "Google" before "BigQuery"

**Comment by nagachika** [comment]
Add newline and refine message was done by #18.

**Comment by kazunori279** [comment]
Confirmed!
