### ISSUE TITLE
Is the NYC Citi Bike time slider correct?

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#60]
When you trying the page, you see traffic peak at around 4am and no traffic around 6pm. Isn't it strange?

**Comment by nagachika** [comment]
My rough analysis with the query below shows that the peak exists at 0AM and 10AM and it stay high during midnight. In contrast usages are very low at evening (18-20PM).

```
SELECT
  HOUR(DATE_ADD(starttime,  -8, "HOUR")) AS hour,
  COUNT(*) as count
FROM
  [bigquery-public-data:new_york.citibike_trips]
GROUP BY
  hour
ORDER BY
  hour
```

**Comment by nagachika** [comment]
... and now I doubt that the table `bigquery-public-data:new_york.citibike_trips` contains TIMESTAMP data without consideration about timezone.
Shifting the time +8 hour seems natural distribution...
I'd like to shift hour in query for instance.

**Comment by nagachika** [comment]
Now I tweaked the weights in  UDF to shift time +8 hours.

**Comment by kazunori279** [comment]
Thanks, now it looks like the peak time is at 0am. Maybe there's still 12 hours difference?

**Comment by nagachika** [comment]
I don't think so. Maybe the citi bikes are used often during night because the public transport is not available.

**Comment by kazunori279** [comment]
Got it!
