### ISSUE TITLE
Can we show the accuracy on the demand forecast?

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#62]
I can imagine that many people as about the accuracy of the forecast. Is that possible to show accuracy?

**Comment by nagachika** [comment]
We have residual error on test dataset in general. But it's difficult to know how the error is on specified conditions. I mean we can display error (RSME) for result page but it cannot vary on the conditions user selected.

**Comment by kazunori279** [comment]
yeah... I just noticed that the conditions you specify are a hypothetical case and there's no real case to evaluate the error.
