### ISSUE TITLE
Project Configuration

### ISSUE THREAD

**Issue by detroittigers** [groovenauts/QueryItSmart#64]
Hello,

Is there any additional setup that I should be aware of when attempting to configure the project other than adding the service_account.json file?  Are there any specific privileges that I should give the user or items that need to be setup in Google Cloud?  

Below are a few of the errors that I am receiving when attempting to run the project.

Thank you!

Error { ApiError
    at Object.parseHttpRespBody (/usr/app/node_modules/@google-cloud/common/src/util.js:192:30)
    at Object.handleResp (/usr/app/node_modules/@google-cloud/common/src/util.js:132:18)
    at /usr/app/node_modules/@google-cloud/common/src/util.js:466:12
    at Request.onResponse [as _callback] (/usr/app/node_modules/retry-request/index.js:120:7)
    at Request.self.callback (/usr/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/app/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
  code: 404,
  errors: 
   [ { domain: 'global',
       reason: 'notFound',
       message: 'Not found: Table gnext-0:wikimedia.image_vectors' } ],
  response: undefined,
  message: 'Not found: Table gnext-0:wikimedia.image_vectors' }

---------

{"code":403,"errors":[{"domain":"global","reason":"accessDenied","message":"Access Denied: BigQuery BigQuery
: Error getting metadata for external code resource, please verify you have provided a valid path and
/or that you have access to the resource: gs://queryit_smart/citibike/udf/weights1.js"}],"message":"Access
 Denied: BigQuery BigQuery: Error getting metadata for external code resource, please verify you have
 provided a valid path and/or that you have access to the resource: gs://queryit_smart/citibike/udf/weights1
.js"}

**Comment by nagachika** [comment]
Thank you for your interest. It's a fault in query. It should includes project specification in table name. I'll fix it later.
Anyway, the tables using in this demo isn't in a public datasets. So you cannot run this demo in your local environment now. We'll make it public after the demo is releases. Please stay tuned.

**Comment by nagachika** [comment]
@detroittigers Now you can run on your GCP project with service account JSON key and API Key. Please see README.md to find instructions to build and run demo application.
