### ISSUE TITLE
Change the temperature selection to relative index on the forecast page

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#65]
Currently, the default value for temperature is set to 20F which is 0 degree in Celsius. Nobody would use bikes.

But it's hard to find a default value on the temperature selection, as it should be changed based on the month in a year.

Can we change it to a relative index, such as:

- +2 degree
- +1 degree
- Average
- -1 degree
- -2 degree

For -10 to +10 ? So that it'll be much fun for users to see how hot/cold day would affect the usage.

**Comment by nakanori** [comment]
Done by #69
