### ISSUE TITLE
Add "Show SQL" button at the search results

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#7]
For all search results (image, text and forecast), add "Show SQL" button that pops up a SQL statement for the query.

**Comment by kazunori279** [comment]
And also add the following on the SQL pop up.

"Search 'QueryIt Smart' on GitHub to learn more."

**Comment by nagachika** [comment]
Added by https://github.com/groovenauts/QueryItSmart/pull/17.

**Comment by kazunori279** [comment]
- Make the SQL much easier to read, by darkening the backgrond
- Remove #standardSQL
- Format the SQL with the formatter of BQ web UI
- Use bigger font and color for the last sentence "Search..."

**Comment by nakanori** [comment]
Done by #35

**Comment by kazunori279** [comment]
Currently the Show SQL button doesn't work

**Comment by nagachika** [comment]
Fixed at https://github.com/groovenauts/QueryItSmart/pull/44/commits/1ea8e7f68d189d99659d6c5e28fc89935477d05f
