### ISSUE TITLE
The tensor flow files are not accesible 

### ISSUE THREAD

**Issue by navacron** [groovenauts/QueryItSmart#79]
Get the following error when trying to copy

gsutil cp gs://queryit_smart/citibike/udf/tensor.js .
AccessDeniedException: 403 Caller does not have storage.objects.list access to bucket queryit_smart.

**Comment by nagachika** [comment]
@navacron Hi, thank you for your interest.
I've forgotten to change ACL of UDF files for NYC Citi Bike demand forecast.
I just make them publicly readable.
Please try again.
Thanks.
