### ISSUE TITLE
Modify "Finished" page

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#8]
- Replace the label from "Finished!" to "Finished"
- Keep showing the labels etc. Not clearing after a few seconds
- Add other info: 
-- xxx images and xxx GBs processed in xxx seconds with Google BigQuery

**Comment by nagachika** [comment]
> "xxx images and ..."

There are 1,127,714 records in target table now.
To display `1.12M images and ...` is enough? The exact number should be shown?

**Comment by kazunori279** [comment]
The exact number would be great.

**Comment by kazunori279** [comment]
Also, please insert new line between "xx GBs proceeced" and "in xx seconds".

**Comment by nagachika** [comment]
This is done by #18.
