### ISSUE TITLE
Error building docker image

### ISSUE THREAD

**Issue by naveed-hearst** [groovenauts/QueryItSmart#80]
When i run docker build -t queryit-smart:latest getting these errors

ESC[0mESC[91mnpm ERR! Refusing to delete /usr/local/bin/yarn: node_modules/npm/bin/npm-cli.js symlink target is not controlled by npm /usr/local
npm ERR!ESC[0mESC[91m File exists: /usr/local/bin/yarn
npm ERR! Move it away, and try again.

[docker.txt](https://github.com/groovenauts/QueryItSmart/files/843073/docker.txt)
[doker-error.txt](https://github.com/groovenauts/QueryItSmart/files/843074/doker-error.txt)

**Comment by navacron** [comment]
accidentally posted from other account. please reply to me if there is a resolution.

**Comment by nagachika** [comment]
@navacron Hi, thank you for your interest.
I've confirmed that docker build upon the latest node:latest docker image run into the same error.
I will investigate the error and fix it, or pin down the base image tag(version). Please stay tuned.

**Comment by nagachika** [comment]
https://github.com/groovenauts/QueryItSmart/commit/8f37a5bf86c70c9a71178cc1c23286e970ab0c2e should fix this issue.
@navacron please try again.
