### ISSUE TITLE
Some of the files in GCS are not accessable.

### ISSUE THREAD

**Issue by ldxstc** [groovenauts/QueryItSmart#81]
I found that following files are not shared publicly:
gs://queryit_smart/citibike/udf/*
gs://queryit-smart-ml/vgg16.tfmodel
gs://queryit-smart-us-east1/citibike/training_data.csv

The first set of files blocking running the demo locally. And the others prevents others from training the models themselves.

Thanks,

**Comment by nagachika** [comment]
Hi, thank you for your interest.

I publish the files `gs://queryit_smart/citibike/udf/*` and `gs://queryit-smart-ml/vgg16.tfmodel`

For `gs://queryit-smart-us-east1/citibike/training_data.csv` it was accidentally embedded in models/citibike/trainer.py module. I'd like to make it possible to specify the training file with command line. You can create training data from public datasets on BigQuery. I'd like to add the instruction too.

**Comment by nagachika** [comment]
Hi, I'm sorry for my long absence.

Now you can specify the training data via `--training_csv` for `models/citibike/trainer.py`.
And I have just made `gs://queryit-smart-us-east1/citibike/training_data.csv` public for reference.
