### ISSUE TITLE
Bigquery table names are missing bucket name.

### ISSUE THREAD

**Issue by ldxstc** [groovenauts/QueryItSmart#82]
In QueryItSmart/data/queries.json, following table name need to be prefixed with their bucket names:

wikimedia.pd_image_vectors
wikimedia.image_vectors_1

**Comment by nagachika** [comment]
@ldxstc Thank you for your interest and report.
I added project id prefix in image search queries at https://github.com/groovenauts/QueryItSmart/commit/034191c518c9b5dda1b83540df3c7cd13dd312cd
