### ISSUE TITLE
Change fonts to the original

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/QueryItSmart#9]
Change the UI font to any closer font to the original QueryIt UI.

**Comment by nagachika** [comment]
Done by  #19.

**Comment by kazunori279** [comment]
Sorry I should have specified in detail. Can you use

- Robot Light for labels (such as Searching, Finished, Wikimedia Commons Images, Buttons)
- Robot Thin for others

**Comment by nagachika** [comment]
We plan to use different fonts on each sub-category of demo (Image, Text, Demand forecast).
Do you like to use the same font on all pages on the demos?

**Comment by kazunori279** [comment]
You can change fonts, but please try to reproduce the look & feel of the original QueryIt (which uses Roboto Thin for most of the texts)

**Comment by kazunori279** [comment]
Confirmed it's fixed.
