### ISSUE TITLE
broken link in README

### ISSUE THREAD

**Issue by broady** [groovenauts/QueryItSmart#90]
![image](https://user-images.githubusercontent.com/24982/32521437-60ace272-c3c8-11e7-87bb-e8820e0a1e3d.png)

This link is broken.

/cc @kazunori279

**Comment by nagachika** [comment]
Thank you for your report.
I have found the new URL on https://github.com/kazunori279/cloudml-demo/blob/master/Next17%20Similarity%20Search%20on%20Stack%20Overflow.ipynb
