### ISSUE TITLE
Request to add a license to repo

### ISSUE THREAD

**Issue by rarsan** [groovenauts/QueryItSmart#91]
Thank you for putting together this fantastic demo showcasing BigQuery & Cloud ML Engine!

Could you please add a license (e.g [MIT License](https://choosealicense.com/licenses/mit/)) so others can use, modify and contribute back?
Here are some GitHub docs on how to add a license to a repo:
- https://help.github.com/articles/adding-a-license-to-a-repository/
- https://help.github.com/articles/licensing-a-repository/

**Comment by nagachika** [comment]
Thank you for your attention for QueryIt Smart!
And thank you for your notice.
I will add `LICENSE` file into the repo after some discussion with the repo members.

**Comment by nagachika** [comment]
@rarsan I added `LICENSE` file at https://github.com/groovenauts/QueryItSmart/commit/430472ce023082675fa0892fe34d673d19a26b5e.

**Comment by rarsan** [comment]
Thank you @nagachika and team.
