### ISSUE TITLE
CREATE MODEL

### ISSUE THREAD

**Issue by saiaman** [groovenauts/QueryItSmart#97]
Can you provide sample CREATE MODEL syntax in order to register mobilenet model ?
I didn't found it in the documentation of bigquery.

Thanks

**Comment by nagachika** [comment]
Hi, thank you for your interest!

Unfortunately BigQuery ML feature importing TensorFlow model was still stay alpha phase.
See GCP Blog https://cloud.google.com/blog/products/ai-machine-learning/all-ai-announcements-from-google-next19-the-smartest-laundry-list

**Comment by nagachika** [comment]
You can see the example query for importing TensorFlow model in Cloud Next session video.
https://youtu.be/DnlG4frLKmw?t=573 (at 9:33-)

**Comment by saiaman** [comment]
Thanks. Anyway to subsribe alpha program?
Or i won’t be able to test this repository with other data?

**Comment by nagachika** [comment]
I think you can touch with BigQuery ML team to get alpha program, but I don't know what channels are official. Maybe the email shown on the Cloud Next session video above can reach them.
