### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by saiaman** [groovenauts/QueryItSmart#98]
Hello i'm trying to use the demo, but got a server error : Not found: Dataset {PROJECTID}:bqml was not found in location US.
Any way to patch this ?

**Comment by nagachika** [comment]
Did you try to deploy the demo onto your own GCP project?
You should create BigQuery ML model on your own GCP project with `CREATE MODEL...`. Alhough it's an alpha feature now. see https://github.com/groovenauts/QueryItSmart/issues/97.
